name: CI to DockerHub

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:${{ github.run_number }}
      - name: Login to DockerHub 
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push Docker Image to DockerHub
        run: |
          docker tag $IMAGE_NAME:${{ github.run_number }} 
          docker push $IMAGE_NAME:${{ github.run_number }}

# problem with credential auth ?